/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcialu3.GUI;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import parcialu3.BO.usuariosBO;
import parcialu3.Connection.cConexion;
import parcialu3.DAO.UsuariosDAO;
/**
 *E:\archivo-1-25082015
 * @author SAMSUNG
 */
public class Usuarios extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{
                
            },
            new String[]{
                "Código", "Nombres", "Apellidos", "Dirección", "Teléfono", "Correo", "Sexo", "Estado", "Ciudad","Foto"
            });
    
    int x, y;
    usuariosBO oUserBO = new usuariosBO();
    UsuariosDAO oUserDAO = new UsuariosDAO();
    JFileChooser SelecImg;
    ImageIcon ii;
    ImageIcon iImg;
    cConexion con = new cConexion();
    private TableRowSorter trsFiltro;
    
    String rArch;
    
    public Usuarios() {
        setUndecorated(true);
        initComponents();
        Shape shp = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 15, 15);
        AWTUtilities.setWindowShape(this, shp);
        plBar.setBackground(Color.DARK_GRAY);
        plBar.setFocusable(false);
        plBar.setOpaque(true);
        lblTitleBar.setForeground(Color.WHITE);
        lblTitleBar.setFocusable(false);

        ii = new ImageIcon("src\\Imagenes\\Fastfm.png");
        lblIco.setIcon(ii);
        
        btnMin.setFocusable(false);
        btnMax.setFocusable(false);

        btnDelete.setEnabled(false);
        btnModificar.setEnabled(false);
        
        setLocationRelativeTo(null);
        ActualizarTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxCiudad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        lblImage = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        ftxtTelefono = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtFiltro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        plBar = new javax.swing.JPanel();
        btnMax = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        lblTitleBar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblIco = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));

        jLabel3.setText("Código:");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Aguascalientes", "Baja California", "Baja California Sur", "Veracruz", "Chiapas", "Guanajuato", "Jalisco", "Quintana Roo", "Campeche", "Yucatán" }));
        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombres:");

        cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--" }));

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Correo:");

        jLabel6.setText("Estado:");

        jLabel7.setText("Ciudad:");

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });

        jLabel8.setText("Dirección:");

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        jLabel9.setText("Teléfono:");

        jLabel10.setText("Sexo:");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Masculino", "Femenino" }));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Foto");
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblImageMousePressed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette1.png"))); // NOI18N
        btnGuardar.setText("   Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close-button-icon-928.png"))); // NOI18N
        btnCancelar.setText("    Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/security1.png"))); // NOI18N
        btnDelete.setText("   Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(153, 153, 153));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/computing-cloud1.png"))); // NOI18N
        btnModificar.setText("   Actualizar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        txtCodigo.setEnabled(false);

        try {
            ftxtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### - ### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombres))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ftxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCorreo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(80, 80, 80)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ftxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnModificar)
                        .addComponent(btnCancelar))
                    .addComponent(btnGuardar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos", jPanel1);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_icon.png"))); // NOI18N
        jLabel11.setText("Buscar:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11))
        );

        tblDatos.setModel(dtm);
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuarios", jPanel2);

        plBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                plBarMouseDragged(evt);
            }
        });
        plBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                plBarMousePressed(evt);
            }
        });

        btnMax.setBackground(new java.awt.Color(255, 0, 0));
        btnMax.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnMax.setForeground(new java.awt.Color(255, 255, 255));
        btnMax.setText("x");
        btnMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxActionPerformed(evt);
            }
        });

        btnMin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnMin.setText("_");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        lblTitleBar.setText("Usuarios");

        javax.swing.GroupLayout plBarLayout = new javax.swing.GroupLayout(plBar);
        plBar.setLayout(plBarLayout);
        plBarLayout.setHorizontalGroup(
            plBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plBarLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblIco)
                .addGroup(plBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plBarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(plBarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin)
                .addGap(4, 4, 4)
                .addComponent(btnMax)
                .addGap(6, 6, 6))
        );
        plBarLayout.setVerticalGroup(
            plBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plBarLayout.createSequentialGroup()
                .addGroup(plBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMin)
                    .addComponent(btnMax)
                    .addComponent(lblTitleBar)
                    .addComponent(jLabel1)
                    .addComponent(lblIco))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(plBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnMaxActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinActionPerformed

    private void plBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plBarMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_plBarMouseDragged

    private void plBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plBarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_plBarMousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(txtNombres.getText().length()!=0&&txtApellidos.getText().length()!=0&&txtDireccion.getText().length()!=0&&ftxtTelefono.getText().length()!=0&&txtCorreo.getText().length()!=0&&lblImage.getIcon()!=null){
        int i = oUserDAO.addU(DataCollections());
        if(i==1){
            JOptionPane.showMessageDialog(null,"Datos Guardados Exitosamente","Guardar",JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            ActualizarTabla();
        }
        else{
            JOptionPane.showMessageDialog(null,"Error","Guardar",JOptionPane.WARNING_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(null,"Error ingrese datos","Campos vacíos",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtCodigo.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtDireccion.setText("");
        ftxtTelefono.setText("");
        txtCorreo.setText("");
        cbxSexo.setSelectedItem("--Seleccione--");
        cbxEstado.setSelectedItem("--Seleccione--");
        lblImage.setIcon(null);
        
        btnDelete.setEnabled(false);
        btnModificar.setEnabled(false);
        
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private void lblImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMousePressed
        lblImage.setIcon(null);
        SelecImg = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG,JPG","png","jpg");
        try{
            SelecImg.setFileFilter(filter);
        if (SelecImg.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File arch = (File) SelecImg.getSelectedFile();
            rArch = arch.getPath();
            System.out.println(rArch);
            iImg = new ImageIcon(((new ImageIcon(rArch)).getImage()).getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_SMOOTH));
            lblImage.setIcon(iImg);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_lblImageMousePressed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        try{
        txtFiltro.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtFiltro.getText());
                txtFiltro.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tblDatos.getModel());
        tblDatos.setRowSorter(trsFiltro);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        try{
        JTable target = (JTable)evt.getSource();
        txtCodigo.setText(target.getValueAt(target.getSelectedRow(), 0).toString());
        txtNombres.setText(target.getValueAt(target.getSelectedRow(), 1).toString());
        txtApellidos.setText(target.getValueAt(target.getSelectedRow(), 2).toString());
        txtDireccion.setText(target.getValueAt(target.getSelectedRow(), 3).toString());
        ftxtTelefono.setText(target.getValueAt(target.getSelectedRow(), 4).toString());
        txtCorreo.setText(target.getValueAt(target.getSelectedRow(), 5).toString());
        cbxSexo.setSelectedItem(target.getValueAt(target.getSelectedRow(), 6).toString());
        cbxEstado.setSelectedItem(target.getValueAt(target.getSelectedRow(), 7).toString());
        cbxCiudad.setSelectedItem(target.getValueAt(target.getSelectedRow(), 8).toString());
        String foto = target.getValueAt(target.getSelectedRow(), 9).toString();
        
        iImg = new ImageIcon(((new ImageIcon(foto)).getImage()).getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_SMOOTH));
        lblImage.setIcon(iImg);
        
        btnDelete.setEnabled(true);
        btnModificar.setEnabled(true);
        
        btnGuardar.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tblDatosMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
        int i = oUserDAO.deleteU(DataCollections());
        if(i==1){
            JOptionPane.showMessageDialog(null,"Datos Eliminados Exitosamente","Eliminar",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null,"Error","Eliminar",JOptionPane.WARNING_MESSAGE);
        }
        ActualizarTabla();
        limpiar();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try{
        int i = oUserDAO.updateU(DataCollections());
        if(i==1){
            JOptionPane.showMessageDialog(null,"Datos Actualizados Exitosamente","Modificar",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null,"Error","Modificar",JOptionPane.WARNING_MESSAGE);
        }
        ActualizarTabla();
        limpiar();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        try{
        switch((String)cbxEstado.getSelectedItem()){
            case "--Seleccione--":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"--Seleccione--"}));
                
            break;
            
            case "Aguascalientes":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Aguascalientes"}));
                
            break;
            
            case "Baja California":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Ensenada","Mexicali","Tijuana"}));
                
            break;
            
            case "Baja California Sur":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"La Paz","Los Cabos"}));
                
            break;
            
            case "Veracruz":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Veracruz","Córdoba",
                    "Orizaba","Xalapa","Poza Rica","Coatzacoalcos","Minatitlán"}));
                
            break;
            
            
            case "Chiapas":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Tuxtla Gutiérrez",
                    "Tapachula"}));
                
            break;
            
            case "Guanajuato":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Celaya",
                    "Guanajuato","Irapuato","León","La Piedad­Pénjamo","San Francisco del Rincón","Salamanca"}));
                
            break;
            
            case "Jalisco":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Guadalajara","Ocotlán","Puerto Vallarta"}));
                
            break;
            
            case "Quintana Roo":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Cancún","Chetumal"}));
                
            break;
            
            case "Campeche":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Campeche",
                    "Ciudad del Carmen"}));
                
            break;
            
            case "Yucatán":
                cbxCiudad.removeAllItems();
                cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Mérida"}));
                
            break;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        try{
        char s = evt.getKeyChar();
        if(Character.isDigit(s)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Error, Ingrese valores de tipo texto","Tipo de datos",JOptionPane.WARNING_MESSAGE);
        }
        if(Character.isUpperCase(s)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Error, Ingrese minúsculas","Tipo de datos",JOptionPane.WARNING_MESSAGE);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        try{
        char s = evt.getKeyChar();
        if(Character.isDigit(s)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Error, Ingrese valores de tipo texto","Tipo de datos",JOptionPane.WARNING_MESSAGE);
        }
        if(Character.isUpperCase(s)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Error, Ingrese minúsculas","Tipo de datos",JOptionPane.WARNING_MESSAGE);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        try{
        char s = evt.getKeyChar();
        if(Character.isUpperCase(s)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Error, Ingrese minúsculas","Tipo de datos",JOptionPane.WARNING_MESSAGE);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    public usuariosBO DataCollections() {
        try{
        oUserBO.setClave(txtCodigo.getText());
        oUserBO.setNombres(txtNombres.getText());
        oUserBO.setApellidos(txtApellidos.getText());
        oUserBO.setDireccion(txtDireccion.getText());
        oUserBO.setTelefono(ftxtTelefono.getText());
        oUserBO.setCorreo(txtCorreo.getText());
        oUserBO.setSexo((String) cbxSexo.getSelectedItem());
        oUserBO.setEstado((String) cbxEstado.getSelectedItem());
        oUserBO.setCiudad((String) cbxCiudad.getSelectedItem());
        oUserBO.setFoto(rArch);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
//catch(Exception e){return 0;}
        return oUserBO;
    }
     
    public void limpiar(){
        try{
        txtCodigo.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtDireccion.setText("");
        ftxtTelefono.setText("");
        txtCorreo.setText("");
        cbxSexo.setSelectedItem("--Seleccione--");
        cbxEstado.setSelectedItem("--Seleccione--");
        lblImage.setIcon(null);
        
        btnDelete.setEnabled(false);
        btnModificar.setEnabled(false);
        
        btnGuardar.setEnabled(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void ActualizarTabla(){
        try{
        tblDatos.setModel(oUserDAO.Buscar());
        tblDatos.updateUI();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void filtro(){
        try{
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtFiltro.getText(),0,1,2,3,4,5,6,7,8,9));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, "+e,"Error",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMax;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JFormattedTextField ftxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblIco;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTitleBar;
    private javax.swing.JPanel plBar;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
